### ISSUE TITLE
No config.json for Alpha-VLLM/WeMix-LLaMA2-V2-70B

### ISSUE THREAD

**Issue by cpaaax** [Alpha-VLLM/WeMix-LLM#2]
There is no config.json for [Alpha-VLLM/WeMix-LLaMA2-V2-70B](https://huggingface.co/Alpha-VLLM/WeMix-LLaMA2-V2-70B/tree/main). Could you help me check that?

**Comment by csuhan** [comment]
Do you mean [https://huggingface.co/Alpha-VLLM/WeMix-LLaMA2-70B/blob/main/params.json]()?
